#!/bin/bash

if [ ! -f /etc/collector/.initialized ]; then
    
    /opt/collector-core/bin/pycollector system --write-config

    cd /opt/collector-core || (echo "ERROR: unable to change to working directory" && exit 1)
    
    ansible-playbook ./install.yml

    RET=$?
    
    if [ $RET -eq 0 ]; then
        echo "SUCCESS: configured initial collector state"
        touch /etc/collector/.initialized
    fi
    exit $RET
fi

exit 0
