name: Security Audit

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run Dependency Audit
        run: cargo audit

      - name: Check Licenses and Bans
        uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe
        with:
          command: check

  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable
          components: clippy
      - name: Run Clippy
        run: cargo clippy -- -D warnings